=== Ournet/embed-provides-data/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/ournet/embed-provides-data/schema.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "id",
      "url",
      "embeds",
      "links"
    ],
    "properties": {
      "id": {
        "$id": "#/items/properties/id",
        "type": "string",
        "title": "The Id Schema",
        "examples": [
          "youtube"
        ],
        "pattern": "^[a-z0-9.-]{2,30}$"
      },
      "url": {
        "$id": "#/items/properties/url",
        "type": "string",
        "title": "The Url Schema",
        "examples": [
          "https://www.youtube.com"
        ]
      },
      "item_id": {
        "$id": "#/items/properties/item_id",
        "type": "string",
        "title": "The item_id Schema",
        "default": "string",
        "examples": [
          "number"
        ],
        "enum": [
          "number",
          "string"
        ]
      },
      "embeds": {
        "$id": "#/items/properties/embeds",
        "type": "array",
        "title": "The Embeds Schema",
        "items": {
          "$id": "#/items/properties/embeds/items",
          "type": "string",
          "title": "The Items Schema",
          "examples": [
            "https://www.youtube.com/embed/{ID}",
            "https://www.youtube-nocookie.com/embed/{ID}"
          ]
        }
      },
      "links": {
        "$id": "#/items/properties/links",
        "type": "array",
        "title": "The Links Schema",
        "items": {
          "$id": "#/items/properties/links/items",
          "type": "string",
          "title": "The Items Schema",
          "examples": [
            "https://www.youtube.com/watch?v={ID}",
            "https://youtu.be/{ID}",
            "youtube.com/v/{ID}",
            "youtube.com/vi/{ID}",
            "youtube.com/?v={ID}",
            "youtube.com/?vi={ID}"
          ]
        }
      }
    }
  }
}

=== Ournet/embed-provides-data/video-providers.json
[
  {
    "id": "youtube",
    "url": "https://www.youtube.com",
    "embeds": [
      "https://www.youtube.com/embed/{ID}",
      "https://www.youtube-nocookie.com/embed/{ID}"
    ],
    "links": [
      "https://www.youtube.com/watch?v={ID}",
      "https://youtu.be/{ID}",
      "youtube.com/v/{ID}",
      "youtube.com/vi/{ID}",
      "youtube.com/?v={ID}",
      "youtube.com/?vi={ID}"
    ]
  },
  {
    "id": "vimeo",
    "url": "https://vimeo.com",
    "item_id": "number",
    "embeds": [
      "https://player.vimeo.com/video/{ID}"
    ],
    "links": [
      "https://vimeo.com/{ID}"
    ]
  },
  {
    "id": "videopress",
    "url": "https://videopress.com",
    "embeds": [
      "https://videopress.com/embed/{ID}"
    ],
    "links": [
      "https://videopress.com/v/{ID}"
    ]
  }
]
